### ISSUE TITLE
undefinded license

### ISSUE THREAD

**Issue by thatsimpressive** [qbcore-framework/qb-cityhall#13] opened 2021-08-12 16:54 UTC
This appears after receiving the weapons license - https://i.imgur.com/UYzSeD6.png

**Comment by ihyajb** [comment] 2021-08-14 19:47
Could not reproduce the issue. Try updating all your scripts, weapons license has to do with multiple different scripts.

**Comment by Developer-Bear** [comment] 2021-08-15 02:48
Tested on fresh build, could not reproduce issue.

**Comment by thatsimpressive** [comment] 2021-08-15 03:33
Updated the addon to the latest version, and now the issue has been resolved.

**Comment by ihyajb** [comment] 2021-08-15 04:01
if the issue has been solved please close this so it can be moved to the right category. Thank you

**Closed** 2021-08-15 04:28 UTC
